services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=FastData@Test123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=FastData@Test123
    ports:
      - "3306:3306"
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
